"""20221207112752

Revision ID: 21afb3dab36f
Revises: 
Create Date: 2022-12-07 10:27:52.485944

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '21afb3dab36f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_items_sub_title', table_name='items')
    op.drop_column('items', 'sub_title')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('items', sa.Column('sub_title', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_index('ix_items_sub_title', 'items', ['sub_title'], unique=False)
    # ### end Alembic commands ###
